---
apiVersion: v1
kind: Template
metadata:
  name: service-template
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        external: ${SERVICE}
        app:  ${APP_NAME}
      name: ${APP_NAME}
    spec:
      ports:
        - port: 9000
          protocol: TCP
          targetPort: 9000
          name: datasvc-port
      selector:
        name: ${SERVICE}
      sessionAffinity: None
      type: ClusterIP
parameters:
  - name: SERVICE
    displayName: Service Name
    description: Service Name
    required: true
  - name: APP_NAME
    required: true
    description: The app name